namespace DotSpinners
{
    public enum SpinnerTypes
    {
        Dots,
        Dots2,
        DotsScrolling,
        DotsSimple,
        DotsRolling,
        DotsShifter,
        Classic,
        Classic2,
        Ping,
        Balloon,
        Stars,
        Stars2,
        Flag,
        Bar,
        PercentageFive,
        RugCrawler,
        HappyBeast,
        Eyes,
        Ooh,
        Brackets,
        Pulse,
        HashFest,
        Matrix,
        Flippie,
        Loading,
        Unspecified,
        Money,
        Ball,
        Plus,
        Crocodiles
    }
}